sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t peters0019/docker-react -f Dockerfile.dev .

script:
  docker run -e CI=true peters0019/docker-react npm run test